using Orbit.Domain.Common;

namespace Orbit.Application.Common;

public static class AppConstants
{
    public const int MaxSubHabits = 20;
    public const int MaxHabitTitleLength = 200;
    public const int MaxHabitDescriptionLength = 2000;
    public const int MaxHabitEmojiLength = DomainConstants.MaxHabitEmojiLength;
    public const int MaxChecklistItemTextLength = 500;
    public const int MaxHabitDepth = 5;
    public const int MaxTagsPerHabit = 5;
    public const int MaxUserFacts = 50;
    public const int MaxRangeDays = 366;
    public const int DefaultReminderMinutes = 15;
    public const int DefaultFreeMaxHabits = 10;
    public const int DefaultFreeAiMessages = 20;
    public const int DefaultProAiMessages = 500;
    public const int MaxBulkOperationSize = 100;
    public const int MaxGoalsPerHabit = 10;
    public const int MaxHabitsPerGoal = 20;
    public const int MaxGoalDescriptionLength = 500;
    public const int MaxGoalProgressNoteLength = 500;
    public const int ReferralDiscountPercent = 10;
    public const int DefaultMaxReferrals = 10;
    public const int ReferralCompletionThreshold = 3;
    public const int ReferralCompletionWindowDays = 7;
    public const int DefaultOverdueWindowDays = 7;
    public const int MaxScheduledReminders = DomainConstants.MaxScheduledReminders;
    public const int MaxReminderTimes = DomainConstants.MaxReminderTimes;
    public const int MaxReminderMinutesBefore = DomainConstants.MaxReminderMinutesBefore;
    public const int MaxPushSubscriptionsPerUser = 5;
    public const int MaxNotificationsReturned = 50;
    public const int MaxChecklistItems = 50;
    public const int MaxTagNameLength = 50;
    public const int MaxUserNameLength = DomainConstants.MaxUserNameLength;
    public const int MaxLanguageLength = 10;
    public const int MaxVerificationAttempts = 3;
    public const int VerificationAttemptWindowMinutes = 15;
    public const int MaxChatMessageLength = 4000;
    public const int MaxClarificationValueLength = 2048;
    public const int MaxClarificationArgsLength = 16384;
    public const int PendingClarificationTtlMinutes = 30;
    public const int MaxChatHistoryLength = 50_000;
    public const int MaxChatHistoryMessages = 40;
    public const int MaxChatHistoryMessageLength = 4000;
    public const long MaxAudioBytes = 26_214_400;
    public const int MaxAiToolResultTextLength = 12_000;
    public const int MaxCalendarRangeDays = 62;
    public const int MaxSelectedCalendars = 50;
    public const int MaxPageSize = 200;
    public const int AdRewardBonusMessages = 5;
    public const int AdRewardDailyCap = 3;
    public const int MaxStreakFreezesPerMonth = 3;
    public const int MaxStreakFreezesAccumulated = 3;
    public const int StreakDaysPerFreeze = 7;
    public const int MaxStreakLookbackDays = 365;
    public const int MaxSyncWindowDays = 30;
    public const int SyncCleanupMarginDays = 1;
    public const int MaxFriends = 500;
    public const int HandleMinLength = DomainConstants.HandleMinLength;
    public const int HandleMaxLength = DomainConstants.HandleMaxLength;
    public const int MaxCheerNoteLength = DomainConstants.MaxCheerNoteLength;
    public const int MaxReportDetailsLength = DomainConstants.MaxReportDetailsLength;
    public const int MaxCheersPerDay = 20;
    public const int MaxFriendRequestsPerDay = 30;
    public const int MaxReportsPerDay = 20;
    public const int MaxSetHandlePerDay = 5;
    public const int FriendFeedPageSize = 30;
    public const int MaxFriendFeedPageSize = 50;
    public static readonly int[] StreakMilestoneTiers = [7, 14, 30, 90, 100, 365];
    public static readonly string[] SupportedLanguages = ["en", "pt-BR"];
}
