using Orbit.Application.Uploads.Common;

namespace Orbit.Application.Common;

public static partial class ErrorCopy
{
    private static (string Code, string En, string PtBr)[] Validation =>
    [
        (ValidationErrorCodes.AccountabilityHabitLimit, $"You can link at most {AppConstants.MaxAccountabilityHabitsPerUser} habits per pair.", $"Você pode vincular no máximo {AppConstants.MaxAccountabilityHabitsPerUser} hábitos por dupla."),
        (ValidationErrorCodes.HabitIdsRequired, "Habit ids must not be empty.", "Os IDs dos hábitos não podem estar vazios."),
        (ValidationErrorCodes.HabitIdsUnique, "Habit ids must not contain duplicates.", "Os IDs dos hábitos não podem se repetir."),
        (ValidationErrorCodes.VerificationCodeFormat, "Code must be a 6-digit number", "O código deve ter 6 dígitos"),
        (ValidationErrorCodes.ApiKeyNameRequired, "API key name is required.", "O nome da chave de API é obrigatório."),
        (ValidationErrorCodes.ApiKeyNameLength, "API key name must be 50 characters or less.", "O nome da chave de API deve ter no máximo 50 caracteres."),
        (ValidationErrorCodes.ApiKeyScopesRequired, "API key scopes must be non-empty strings.", "As permissões da chave de API não podem estar vazias."),
        (ValidationErrorCodes.ApiKeyScopeInvalid, "API key scope '{PropertyValue}' is not a recognized scope.", "A permissão '{PropertyValue}' da chave de API não é reconhecida."),
        (ValidationErrorCodes.ApiKeyExpiryFuture, "API key expiry must be in the future.", "A validade da chave de API deve estar no futuro."),
        (ValidationErrorCodes.AccessTokenRequired, "Access token is required.", "O token de acesso é obrigatório."),
        (ValidationErrorCodes.LanguageSupported, $"Language must be one of: {string.Join(", ", AppConstants.SupportedLanguages)}", $"O idioma deve ser um destes: {string.Join(", ", AppConstants.SupportedLanguages)}"),
        (ValidationErrorCodes.RefreshTokenFormat, "Refresh token format is invalid.", "O formato do token de atualização é inválido."),
        (ValidationErrorCodes.CalendarSelectionLimit, $"You can select at most {AppConstants.MaxSelectedCalendars} calendars.", $"Você pode selecionar no máximo {AppConstants.MaxSelectedCalendars} agendas."),
        (ValidationErrorCodes.CalendarIdsRequired, "Calendar ids must be non-empty.", "Os IDs das agendas não podem estar vazios."),
        (ValidationErrorCodes.ChallengeTargetPositive, "A goal challenge requires a target count greater than 0.", "Um desafio de meta precisa de uma quantidade maior que 0."),
        (ValidationErrorCodes.StreakChallengeTargetAbsent, "A streak challenge cannot have a target count.", "Um desafio de sequência não pode ter uma quantidade alvo."),
        (ValidationErrorCodes.ChallengeEndDateRequired, "A goal challenge requires an end date.", "Um desafio de meta precisa de uma data de término."),
        (ValidationErrorCodes.ChallengeHabitsRequired, "Link at least one of your habits to the challenge.", "Vincule pelo menos um dos seus hábitos ao desafio."),
        (ValidationErrorCodes.ChallengeHabitLimit, $"You can link at most {AppConstants.MaxHabitsPerChallengeParticipant} habits.", $"Você pode vincular no máximo {AppConstants.MaxHabitsPerChallengeParticipant} hábitos."),
        (ValidationErrorCodes.ChallengeInviteLimit, $"You can invite at most {AppConstants.MaxChallengeParticipants - 1} friends.", $"Você pode convidar no máximo {AppConstants.MaxChallengeParticipants - 1} amigos."),
        (ValidationErrorCodes.ChatMessageRequired, "Message cannot be empty.", "A mensagem não pode estar vazia."),
        (ValidationErrorCodes.ChatMessageLength, $"Message cannot exceed {AppConstants.MaxChatMessageLength} characters.", $"A mensagem deve ter no máximo {AppConstants.MaxChatMessageLength} caracteres."),
        (ValidationErrorCodes.ChatHistoryLimit, $"Chat history cannot exceed {AppConstants.MaxChatHistoryMessages} messages.", $"O histórico da conversa deve ter no máximo {AppConstants.MaxChatHistoryMessages} mensagens."),
        (ValidationErrorCodes.ChatHistoryRole, "Chat history contains an invalid role.", "O histórico da conversa contém um papel inválido."),
        (ValidationErrorCodes.ChatHistoryMessageLength, $"Chat history messages must be between 1 and {AppConstants.MaxChatHistoryMessageLength} characters.", $"As mensagens do histórico devem ter entre 1 e {AppConstants.MaxChatHistoryMessageLength} caracteres."),
        (ValidationErrorCodes.RevisionItemLimit, "At most 500 items may be revised.", "No máximo 500 itens podem ser revisados."),
        (ValidationErrorCodes.RevisionItemIdsUnique, "Item IDs must be unique.", "Os IDs dos itens não podem se repetir."),
        (ValidationErrorCodes.AudioRequired, "Audio file is required.", "O arquivo de áudio é obrigatório."),
        (ValidationErrorCodes.AudioSizeLimit, $"Audio exceeds the maximum size of {AppConstants.MaxAudioBytes / (1024 * 1024)}MB.", $"O áudio excede o tamanho máximo de {AppConstants.MaxAudioBytes / (1024 * 1024)}MB."),
        (ValidationErrorCodes.AudioFormat, "Audio format '{0}' is not supported.", "O formato de áudio '{0}' não é suportado."),
        (ValidationErrorCodes.TemplateItemLimit, $"A checklist template can have at most {AppConstants.MaxChecklistItems} items.", $"Um modelo de checklist pode ter no máximo {AppConstants.MaxChecklistItems} itens."),
        (ValidationErrorCodes.TemplateItemRequired, "Checklist template items must not be empty.", "Os itens do modelo de checklist não podem estar vazios."),
        (ValidationErrorCodes.TemplateItemLength, $"Checklist template item text must not exceed {AppConstants.MaxChecklistItemTextLength} characters.", $"O texto de um item do modelo de checklist deve ter no máximo {AppConstants.MaxChecklistItemTextLength} caracteres."),
        (ValidationErrorCodes.PeriodSupported, "Period must be one of: week, month, quarter, semester, year.", "O período deve ser um destes: week, month, quarter, semester, year."),
        (ValidationErrorCodes.DateRangeOrder, "DateFrom must be on or before DateTo.", "DateFrom deve ser anterior ou igual a DateTo."),
        (ValidationErrorCodes.ClosedPeriodMatch, "Closed period parameters must match the requested period.", "Os parâmetros do período fechado devem corresponder ao período solicitado."),
        (ValidationErrorCodes.ClosedCalendarMonthOnly, "Closed calendar parameters can only be used with the month period.", "Os parâmetros de calendário fechado só podem ser usados com o período month."),
        (ValidationErrorCodes.ClosedYearRange, "ClosedYear must be between 1 and 9999.", "ClosedYear deve estar entre 1 e 9999."),
        (ValidationErrorCodes.ClosedMonthRange, "ClosedMonth must be between 1 and 12.", "ClosedMonth deve estar entre 1 e 12."),
        (ValidationErrorCodes.ClosedMonthDates, "DateFrom and DateTo must match the complete closed calendar month.", "DateFrom e DateTo devem corresponder ao mês completo do calendário fechado."),
        (ValidationErrorCodes.ClosedYearDates, "DateFrom and DateTo must match the complete closed calendar year.", "DateFrom e DateTo devem corresponder ao ano completo do calendário fechado."),
        (ValidationErrorCodes.ClosedWeekDates, "DateFrom and DateTo must match the complete closed calendar week.", "DateFrom e DateTo devem corresponder à semana completa do calendário fechado."),
        (ValidationErrorCodes.DateRangeLimit, $"Date range must not exceed {AppConstants.MaxRangeDays} days.", $"O intervalo de datas deve ter no máximo {AppConstants.MaxRangeDays} dias."),
        (ValidationErrorCodes.StreakGapLimit, "The gap exceeds the streak history window.", "O intervalo excede a janela do histórico de sequência."),
        (ValidationErrorCodes.StreakDateRequired, "Each date is required.", "Cada data é obrigatória."),
        (ValidationErrorCodes.StreakDatesUnique, "Select each date once.", "Selecione cada data uma vez."),
        (ValidationErrorCodes.EventKeyKnown, "Unknown event key.", "A chave do evento é desconhecida."),
        (ValidationErrorCodes.GoalHabitLimit, $"A goal can have at most {AppConstants.MaxHabitsPerGoal} linked habits.", $"Uma meta pode ter no máximo {AppConstants.MaxHabitsPerGoal} hábitos vinculados."),
        (ValidationErrorCodes.BulkHabitsRequired, "Habits list must not be empty", "A lista de hábitos não pode estar vazia"),
        (ValidationErrorCodes.BulkCreateLimit, $"Cannot create more than {AppConstants.MaxBulkOperationSize} habits at once", $"Não é possível criar mais de {AppConstants.MaxBulkOperationSize} hábitos de uma vez"),
        (ValidationErrorCodes.FrequencyQuantityRequired, "Frequency quantity is required when frequency unit is set", "A quantidade de frequência é obrigatória quando a unidade de frequência está definida"),
        (ValidationErrorCodes.BulkTagLimit, $"Cannot assign more than {AppConstants.MaxTagsPerHabit} tags per habit", $"Não é possível atribuir mais de {AppConstants.MaxTagsPerHabit} tags por hábito"),
        (ValidationErrorCodes.BulkHabitIdsRequired, "HabitIds list must not be empty", "A lista de IDs dos hábitos não pode estar vazia"),
        (ValidationErrorCodes.BulkDeleteHabitLimit, $"Cannot delete more than {AppConstants.MaxBulkOperationSize} habits at once", $"Não é possível excluir mais de {AppConstants.MaxBulkOperationSize} hábitos de uma vez"),
        (ValidationErrorCodes.HabitIdRequired, "Habit ID must not be empty", "O ID do hábito não pode estar vazio"),
        (ValidationErrorCodes.BulkItemsRequired, "Items list must not be empty", "A lista de itens não pode estar vazia"),
        (ValidationErrorCodes.BulkFilterRequired, "A bulk habit filter is required.", "Um filtro de hábitos é obrigatório."),
        (ValidationErrorCodes.BulkChangesRequired, "At least one habit change is required.", "Pelo menos uma alteração de hábito é obrigatória."),
        (ValidationErrorCodes.RecurringQuantityPositive, "A recurring frequency requires a positive frequency quantity.", "Uma frequência recorrente precisa de uma quantidade positiva."),
        (ValidationErrorCodes.SubHabitLimit, $"A habit can have at most {AppConstants.MaxSubHabits} sub-habits", $"Um hábito pode ter no máximo {AppConstants.MaxSubHabits} sub-hábitos"),
        (ValidationErrorCodes.SubHabitTitleRequired, "Sub-habit title must not be empty", "O título do sub-hábito não pode estar vazio"),
        (ValidationErrorCodes.SubHabitTitleLength, $"Sub-habit title must not exceed {AppConstants.MaxHabitTitleLength} characters", $"O título do sub-hábito deve ter no máximo {AppConstants.MaxHabitTitleLength} caracteres"),
        (ValidationErrorCodes.GeneralHabitNotBad, "General habits cannot be bad habits", "Hábitos gerais não podem ser hábitos ruins"),
        (ValidationErrorCodes.HabitTagLimit, $"A habit can have at most {AppConstants.MaxTagsPerHabit} tags", $"Um hábito pode ter no máximo {AppConstants.MaxTagsPerHabit} tags"),
        (ValidationErrorCodes.DateRangeOrderLower, "dateTo must be >= dateFrom", "dateTo deve ser posterior ou igual a dateFrom"),
        (ValidationErrorCodes.DateRangeLimitShort, $"Date range must not exceed {AppConstants.MaxRangeDays} days", $"O intervalo de datas deve ter no máximo {AppConstants.MaxRangeDays} dias"),
        (ValidationErrorCodes.CalendarDateRangeLimit, $"Date range must not exceed {AppConstants.MaxCalendarRangeDays} days", $"O intervalo de datas deve ter no máximo {AppConstants.MaxCalendarRangeDays} dias"),
        (ValidationErrorCodes.DateFromRequired, "dateFrom is required", "dateFrom é obrigatório"),
        (ValidationErrorCodes.DateToRequired, "dateTo is required", "dateTo é obrigatório"),
        (ValidationErrorCodes.HabitGoalLimit, $"A habit can have at most {AppConstants.MaxGoalsPerHabit} linked goals.", $"Um hábito pode ter no máximo {AppConstants.MaxGoalsPerHabit} metas vinculadas."),
        (ValidationErrorCodes.PositionsRequired, "Positions list must not be empty", "A lista de posições não pode estar vazia"),
        (ValidationErrorCodes.PositionsUnique, "Positions list must not contain duplicate habit IDs", "A lista de posições não pode conter IDs de hábitos repetidos"),
        (ValidationErrorCodes.ChecklistItemLength, $"Checklist item text must not exceed {AppConstants.MaxChecklistItemTextLength} characters", $"O texto de um item do checklist deve ter no máximo {AppConstants.MaxChecklistItemTextLength} caracteres"),
        (ValidationErrorCodes.DaysDailyOnly, "Days can only be specified for a daily habit (frequency unit Day, quantity 1)", "Dias só podem ser definidos para um hábito diário (unidade Day, quantidade 1)"),
        (ValidationErrorCodes.EndDateRecurringOnly, "An end date requires a recurring habit", "Uma data de término precisa de um hábito recorrente"),
        (ValidationErrorCodes.ScheduledReminderLimit, $"A habit can have at most {AppConstants.MaxScheduledReminders} scheduled reminders", $"Um hábito pode ter no máximo {AppConstants.MaxScheduledReminders} lembretes agendados"),
        (ValidationErrorCodes.ScheduledReminderWhen, "Scheduled reminder 'when' must be 'day_before' or 'same_day'", "O campo 'when' do lembrete deve ser 'day_before' ou 'same_day'"),
        (ValidationErrorCodes.ScheduledRemindersUnique, "Scheduled reminders must not contain duplicate entries", "Os lembretes agendados não podem se repetir"),
        (ValidationErrorCodes.ReminderTimeLimit, $"A habit can have at most {AppConstants.MaxReminderTimes} reminder times", $"Um hábito pode ter no máximo {AppConstants.MaxReminderTimes} horários de lembrete"),
        (ValidationErrorCodes.ReminderTimeRange, $"Reminder times must be between 0 and {AppConstants.MaxReminderMinutesBefore} minutes before the due time", $"Os lembretes devem ser de 0 a {AppConstants.MaxReminderMinutesBefore} minutos antes do horário previsto"),
        (ValidationErrorCodes.ReminderTimesUnique, "Reminder times must not contain duplicate values", "Os horários de lembrete não podem se repetir"),
        (ValidationErrorCodes.RelativeRemindersValid, "Relative reminders must be unique and have a valid offset or local time", "Os lembretes relativos não podem se repetir e devem ter um intervalo ou horário local válido"),
        (ValidationErrorCodes.GeneralFrequencyUnitAbsent, "General habits cannot have a frequency unit", "Hábitos gerais não podem ter unidade de frequência"),
        (ValidationErrorCodes.GeneralFrequencyQuantityAbsent, "General habits cannot have a frequency quantity", "Hábitos gerais não podem ter quantidade de frequência"),
        (ValidationErrorCodes.GeneralDaysAbsent, "General habits cannot have specific days", "Hábitos gerais não podem ter dias específicos"),
        (ValidationErrorCodes.CalendarDateValid, "Date must be a valid calendar date", "A data deve ser uma data válida do calendário"),
        (ValidationErrorCodes.ChecklistItemLimit, $"A checklist can have at most {AppConstants.MaxChecklistItems} items", $"Um checklist pode ter no máximo {AppConstants.MaxChecklistItems} itens"),
        (ValidationErrorCodes.WeekStartOnboarding, "Week start day must be 0 (Sunday) or 1 (Monday).", "O início da semana deve ser 0 (domingo) ou 1 (segunda-feira)."),
        (ValidationErrorCodes.HandleFormat, "Handle must be 3-20 characters using only letters, numbers, or underscores.", "O nome de usuário deve ter de 3 a 20 caracteres, usando apenas letras, números ou sublinhados."),
        (ValidationErrorCodes.ProfileNameLength, $"Name must be at most {AppConstants.MaxUserNameLength} characters", $"O nome deve ter no máximo {AppConstants.MaxUserNameLength} caracteres"),
        (ValidationErrorCodes.WeekStartDay, "WeekStartDay must be 0 (Sunday) or 1 (Monday).", "WeekStartDay deve ser 0 (domingo) ou 1 (segunda-feira)."),
        (ValidationErrorCodes.CheersDirection, "Direction must be 'received' or 'sent'.", "A direção deve ser 'received' ou 'sent'."),
        (ValidationErrorCodes.FeedCursorFormat, "Cursor is malformed.", "O cursor está malformado."),
        (ValidationErrorCodes.FriendIdentifierExclusive, "Provide exactly one of handle or referralCode.", "Informe exatamente um destes: handle ou referralCode."),
        (ValidationErrorCodes.BillingIntervalRequired, "Billing interval is required.", "O intervalo de cobrança é obrigatório."),
        (ValidationErrorCodes.BillingIntervalSupported, "Billing interval must be 'monthly' or 'yearly'.", "O intervalo de cobrança deve ser 'monthly' ou 'yearly'."),
        (ValidationErrorCodes.TagColorFormat, "Color must be a valid hex color (e.g. #FF5733)", "A cor deve ser um código hexadecimal válido (por exemplo, #FF5733)"),
        (ValidationErrorCodes.UploadContentTypeRequired, "Content type is required.", "O tipo de conteúdo é obrigatório."),
        (ValidationErrorCodes.UploadContentTypeSupported, $"Content type must be one of: {string.Join(", ", UploadContentTypes.Allowed)}.", $"O tipo de conteúdo deve ser um destes: {string.Join(", ", UploadContentTypes.Allowed)}."),
        (ValidationErrorCodes.UploadSizePositive, "File size must be greater than zero.", "O tamanho do arquivo deve ser maior que zero."),
        (ValidationErrorCodes.UploadSizeLimit, $"File size must be {UploadContentTypes.MaxSizeBytes} bytes or less.", $"O arquivo deve ter no máximo {UploadContentTypes.MaxSizeBytes} bytes."),
        (ValidationErrorCodes.FactIdsRequired, "FactIds list must not be empty", "A lista de IDs dos fatos não pode estar vazia"),
        (ValidationErrorCodes.BulkDeleteFactLimit, $"Cannot delete more than {AppConstants.MaxBulkOperationSize} facts at once", $"Não é possível excluir mais de {AppConstants.MaxBulkOperationSize} fatos de uma vez"),
        (ValidationErrorCodes.FactIdRequired, "Fact ID must not be empty", "O ID do fato não pode estar vazio"),
        (ValidationErrorCodes.WaitlistLanguageSupported, "Language must be one of: en, pt-BR.", "O idioma deve ser um destes: en, pt-BR."),
        (ValidationErrorCodes.BulkLogLimit, $"Bulk log cannot exceed {AppConstants.MaxBulkOperationSize} items", $"Não é possível registrar mais de {AppConstants.MaxBulkOperationSize} itens de uma vez"),
        (ValidationErrorCodes.BulkSkipLimit, $"Bulk skip cannot exceed {AppConstants.MaxBulkOperationSize} items", $"Não é possível pular mais de {AppConstants.MaxBulkOperationSize} itens de uma vez"),
        ("NotEmptyValidator", "'{PropertyName}' must not be empty.", "'{PropertyName}' deve ser informado."),
        ("NotNullValidator", "'{PropertyName}' must not be empty.", "'{PropertyName}' não pode ser nulo."),
        ("NullValidator", "'{PropertyName}' must be empty.", "'{PropertyName}' deve estar vazio."),
        ("EmailValidator", "'{PropertyName}' is not a valid email address.", "'{PropertyName}' é um endereço de email inválido."),
        ("LengthValidator", "'{PropertyName}' must be between {MinLength} and {MaxLength} characters. You entered {TotalLength} characters.", "'{PropertyName}' deve ter entre {MinLength} e {MaxLength} caracteres. Você digitou {TotalLength} caracteres."),
        ("MaximumLengthValidator", "The length of '{PropertyName}' must be {MaxLength} characters or fewer. You entered {TotalLength} characters.", "'{PropertyName}' deve ser menor ou igual a {MaxLength} caracteres. Você digitou {TotalLength} caracteres."),
        ("RegularExpressionValidator", "'{PropertyName}' is not in the correct format.", "'{PropertyName}' não está no formato correto."),
        ("EqualValidator", "'{PropertyName}' must be equal to '{ComparisonValue}'.", "'{PropertyName}' deve ser igual a '{ComparisonValue}'."),
        ("NotEqualValidator", "'{PropertyName}' must not be equal to '{ComparisonValue}'.", "'{PropertyName}' deve ser diferente de '{ComparisonValue}'."),
        ("PredicateValidator", "The specified condition was not met for '{PropertyName}'.", "'{PropertyName}' não atende a condição definida."),
        ("GreaterThanValidator", "'{PropertyName}' must be greater than '{ComparisonValue}'.", "'{PropertyName}' deve ser superior a '{ComparisonValue}'."),
        ("GreaterThanOrEqualValidator", "'{PropertyName}' must be greater than or equal to '{ComparisonValue}'.", "'{PropertyName}' deve ser superior ou igual a '{ComparisonValue}'."),
        ("LessThanOrEqualValidator", "'{PropertyName}' must be less than or equal to '{ComparisonValue}'.", "'{PropertyName}' deve ser inferior ou igual a '{ComparisonValue}'."),
        ("InclusiveBetweenValidator", "'{PropertyName}' must be between {From} and {To}. You entered {PropertyValue}.", "'{PropertyName}' deve estar entre {From} e {To}. Você digitou {PropertyValue}."),
        ("EnumValidator", "'{PropertyName}' has a range of values which does not include '{PropertyValue}'.", "'{PropertyName}' possui um intervalo de valores que não inclui '{PropertyValue}'."),
        ("ExactLengthValidator", "'{PropertyName}' must be {MaxLength} characters in length. You entered {TotalLength} characters.", "'{PropertyName}' deve ter exatamente {MaxLength} caracteres. Você digitou {TotalLength} caracteres."),
        ("AsyncPredicateValidator", "The specified condition was not met for '{PropertyName}'.", "'{PropertyName}' não atende a condição definida."),
    ];
}
